import './globals.css'
import type {Metadata} from 'next'
import GraphProvider from "@/graphql/GraphProvider";
import Search from "@/app/components/search";
import Header from "@/app/components/header";
import React from "react";


export const metadata: Metadata = {
  title: 'Anime list',
  description: 'Generated by create next app',
}


export default async function RootLayout({children}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="ru">
    <body>
    <GraphProvider>
      <>
        <Header>
          <Search/>
        </Header>
        {children}
      </>
    </GraphProvider>
    </body>
    </html>
  )
}